-- Script generated by USE 2.4.0

!create Roger : Personne
!set Roger.nom := 'Roger'
!set Roger.age := 22
!set Roger.sexe := #Homme

!create Pierre : Personne
!set Pierre.nom := 'Pierre'
!set Pierre.age := 22
!set Pierre.sexe := #Homme

!create Lucille : Personne
!set Lucille.nom := 'Lucille'
!set Lucille.age := 17
!set Lucille.sexe := #Femme

!create Simone : Personne
!set Simone.nom := 'Simone'
!set Simone.age := 45
!set Simone.sexe := #Femme

!create Gerard : Personne
!set Gerard.nom := 'Gerard'
!set Gerard.age := 54
!set Gerard.sexe := #Homme

!create Saturnin : Personne
!set Saturnin.nom := 'Saturnin'
!set Saturnin.age := 65
!set Saturnin.sexe := #Homme

!create Tatiana : Personne
!set Tatiana.nom := 'Tatiana'
!set Tatiana.age := 56
!set Tatiana.sexe := #Femme

!create Linda : Personne
!set Linda.nom := 'Linda'
!set Linda.age := 5
!set Linda.sexe := #Femme

!create Oskar : Personne
!set Oskar.nom := 'Oskar'
!set Oskar.age := 2
!set Oskar.sexe := #Homme
